# Generated by Django 5.1.3 on 2024-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mola', '0002_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='source',
            field=models.CharField(default='GitHub', max_length=50),
        ),
        migrations.AddField(
            model_name='sunfish',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sunfish',
            name='stage',
            field=models.CharField(default='dust', max_length=20),
        ),
    ]
