# Generated by Django 5.1.3 on 2024-11-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mola', '0003_contribution_source_sunfish_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='source',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='sunfish',
        ),
    ]
