# Generated by Django 5.1.3 on 2024-12-02 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mola', '0004_remove_contribution_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunfish',
            name='last_contribution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
