# Generated by Django 5.1.3 on 2024-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mola', '0005_sunfish_last_contribution_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sunfish',
            name='last_processed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
