name: Log Push Events

on:
  push:
    branches:
      - main

jobs:
  log-push-events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log push events
      run: |
        echo "Push event detected on branch: ${{ github.ref_name }}"
        echo "Commit message: ${{ github.event.head_commit.message }}"
        echo "Pusher: ${{ github.event.pusher.name }}"

    - name: Send data to external server
      run: |
        curl -X POST https://your-server-endpoint/api/log-events \
             -H "Content-Type: application/json" \
             -d '{
               "branch": "${{ github.ref_name }}",
               "commit_message": "${{ github.event.head_commit.message }}",
               "pusher": "${{ github.event.pusher.name }}"
             }'
